title: Sandesh Soni | Elixir developer
email: hello@sandeshsoni.com
description: >- # this means to ignore newlines until "baseurl:"
  Freelance Elixir developer. Built tetris kachori game and course. Fullstack consultant. Elixir ELM Reactjs.
  Working remotely from Pune, India.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sandeshsoni.com" # te base hostname & protocol for your site, e.g. http://example.com
email: hello@sandeshsoni.com
twitter_username: iamsandeshsoni
# twitter: iamsandeshsoni
github_username:  sandeshsoni
linkedin_username: sandeshsoni
telegram_username: sandeshsoni

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

  # theme: jekyll-theme-cayman
  # remote_theme: hanuman
  theme: minima
  # theme: hanuman

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics

sass:
    style: compressed

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-135632177-1         # Required - replace with your tracking id
    anonymizeIp: false

    # analytics_id: UA-135632177-1

    permalink: /:title
show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
